# Generated by Django 4.2.4 on 2023-11-01 12:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fit', '0002_food'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=32, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z\\-\\s]*$', 'Only alphanumeric characters and dashes are allowed.')])),
                ('num_sets', models.PositiveIntegerField()),
                ('num_reps', models.PositiveIntegerField()),
                ('exercise_weight', models.PositiveIntegerField()),
                ('exercise_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fit.exerciselog')),
            ],
        ),
    ]
